# Generated by Django 5.0.1 on 2024-02-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travello", "0003_destination_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
    ]
