# Generated by Django 5.0.1 on 2024-02-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travello", "0004_destination_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="city",
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(default="", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travello.destination",
                    ),
                ),
            ],
        ),
    ]
